name: betid
description: A tiny, secure, unique identifier generator for Dart.
version: 1.0.0
repository: https://github.com/odroe/betid

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
